# Generated by Django 5.1.7 on 2025-03-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=200)),
                ('nombre_revista', models.CharField(max_length=100)),
                ('abstracto', models.TextField(blank=True, null=True)),
                ('pais_publicacion', models.CharField(max_length=100)),
                ('ano_publicacion', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escuela', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('empresa_invita', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
            },
        ),
        migrations.CreateModel(
            name='NivelSNII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Niveles SNII',
            },
        ),
        migrations.CreateModel(
            name='RolEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Roles de Evento',
            },
        ),
        migrations.CreateModel(
            name='TipoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Herramientas',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='DetEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.evento')),
            ],
        ),
        migrations.CreateModel(
            name='DetHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.area')),
            ],
            options={
                'verbose_name_plural': 'Investigadores',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='investigadores',
            field=models.ManyToManyField(through='investigators.DetEvento', to='investigators.investigador'),
        ),
        migrations.CreateModel(
            name='DetProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_importancia', models.IntegerField()),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador')),
            ],
        ),
        migrations.CreateModel(
            name='DetLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador')),
            ],
        ),
        migrations.AddField(
            model_name='detevento',
            name='investigador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador'),
        ),
        migrations.CreateModel(
            name='DetArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_autor', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.articulo')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador')),
            ],
            options={
                'unique_together': {('articulo', 'investigador')},
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='investigadores',
            field=models.ManyToManyField(through='investigators.DetArticulo', to='investigators.investigador'),
        ),
        migrations.CreateModel(
            name='JefeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.area')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador')),
            ],
            options={
                'verbose_name_plural': 'Jefes de Área',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('investigadores', models.ManyToManyField(through='investigators.DetLinea', to='investigators.investigador')),
            ],
            options={
                'verbose_name_plural': 'Líneas',
            },
        ),
        migrations.AddField(
            model_name='detlinea',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.linea'),
        ),
        migrations.CreateModel(
            name='NivelEducacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Niveles de Educación',
            },
        ),
        migrations.AddField(
            model_name='investigador',
            name='nivel_edu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.niveleducacion'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('herramientas', models.ManyToManyField(through='investigators.DetHerramienta', to='investigators.herramienta')),
                ('investigadores', models.ManyToManyField(through='investigators.DetProyecto', to='investigators.investigador')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_liderados', to='investigators.investigador')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='detproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.proyecto'),
        ),
        migrations.AddField(
            model_name='detherramienta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.proyecto'),
        ),
        migrations.AddField(
            model_name='detevento',
            name='rol_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.rolevento'),
        ),
        migrations.CreateModel(
            name='SNII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('nivel_snii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.nivelsnii')),
            ],
            options={
                'verbose_name_plural': 'SNII',
            },
        ),
        migrations.AddField(
            model_name='investigador',
            name='snii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigators.snii'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.carrera')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador')),
                ('tipo_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.tipoestudiante')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.tipoevento'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='tipo_herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.tipoherramienta'),
        ),
        migrations.AddField(
            model_name='area',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigators.unidad'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('intentos_login', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('investigador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigators.investigador')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='detlinea',
            unique_together={('linea', 'investigador')},
        ),
        migrations.AlterUniqueTogether(
            name='detproyecto',
            unique_together={('proyecto', 'investigador')},
        ),
        migrations.AlterUniqueTogether(
            name='detherramienta',
            unique_together={('proyecto', 'herramienta')},
        ),
        migrations.AlterUniqueTogether(
            name='detevento',
            unique_together={('evento', 'investigador')},
        ),
    ]
