# Generated by Django 5.1.7 on 2025-03-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='escuela',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
