# Generated by Django 4.2.20 on 2025-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Desertor', 'Desertor'), ('Egresado', 'Egresado'), ('Titulado', 'Titulado')], max_length=50, null=True),
        ),
    ]
