# Generated by Django 4.2.20 on 2025-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0002_estudiante_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='reconocimiento_institucional',
            field=models.BooleanField(default=False),
        ),
    ]
