# Generated by Django 5.1.7 on 2025-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0002_remove_carrera_escuela_estudiante_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveleducacion',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
