# Generated by Django 5.1.7 on 2025-03-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0003_niveleducacion_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveleducacion',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='investigador',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigators.especialidad'),
        ),
    ]
