# Generated by Django 4.2.20 on 2025-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0003_linea_reconocimiento_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('En Revista', 'En Revista'), ('Publicado', 'Publicado')], default='En Proceso', max_length=50),
        ),
    ]
