# Generated by Django 5.1.7 on 2025-03-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0004_remove_niveleducacion_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='snii',
        ),
        migrations.AddField(
            model_name='investigador',
            name='fecha_asignacion_snii',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigador',
            name='nivel_snii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigators.nivelsnii'),
        ),
        migrations.DeleteModel(
            name='SNII',
        ),
    ]
