# Generated by Django 4.2.20 on 2025-04-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0004_articulo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre_revista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
