# Generated by Django 4.2.20 on 2025-04-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0005_alter_articulo_nombre_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_estudiantes_maestria', models.IntegerField(default=0)),
                ('puntos_estudiantes_doctorado', models.IntegerField(default=0)),
                ('puntos_lineas_investigacion', models.IntegerField(default=0)),
                ('puntos_proyectos', models.IntegerField(default=0)),
                ('puntos_articulos', models.IntegerField(default=0)),
                ('puntos_eventos', models.IntegerField(default=0)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('investigador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntaje', to='investigators.investigador')),
            ],
            options={
                'verbose_name_plural': 'Puntajes de Investigadores',
            },
        ),
    ]
