# Generated by Django 5.1.7 on 2025-03-27 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0005_remove_investigador_snii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='investigators.estudiante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='investigador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='investigators.investigador'),
        ),
    ]
