# Generated by Django 5.1.7 on 2025-03-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0007_remove_usuario_id_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('investigador', 'Investigador'), ('estudiante', 'Estudiante')], max_length=15),
        ),
    ]
