# Generated by Django 5.1.7 on 2025-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0008_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
