# Generated by Django 5.1.7 on 2025-04-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigators', '0009_estudiante_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='ano_publicacion',
        ),
    ]
